export const actionTypes = {
  REQUEST_CREATIVE: "REQUEST_CREATIVE",
  REQUESTED_CREATIVE: "REQUESTED_CREATIVE",
  REQUESTED_CREATIVE_ERROR: "REQUESTED_CREATIVE_ERROR",
  LOGGEDIN: "LOGGEDIN",
  LOGOUT: "LOGOUT"
};
